package io.xoana.ikarus

//fun Number.sin(): Number = Math.sin(this.toDouble()).to(this.class)
fun Double.abs(): Double = Math.abs(this)
fun Double.acos(): Double = Math.acos(this)
fun Double.asin(): Double = Math.asin(this)
fun Double.atan(): Double = Math.atan(this)
fun Double.atan2(x: Double): Double = Math.atan2(this, x)
fun Double.cbrt(): Double = Math.cbrt(this)
fun Double.ceil(): Double = Math.ceil(this)
fun Double.clamp(min: Double, max: Double): Double = Math.max(min, Math.min(this, max))
fun Double.copySign(sign: Double): Double = Math.copySign(this, sign)
fun Double.cos(): Double = Math.cos(this)
fun Double.exp(): Double = Math.exp(this)
fun Double.expm1(): Double = Math.expm1(this)
fun Double.exponent(): Int = Math.getExponent(this)
fun Double.floor(): Double = Math.floor(this)
fun Double.IEEEremainder(divisor: Double): Double = Math.IEEEremainder(this, divisor)
fun Double.log(): Double = Math.log(this)
fun Double.log10(): Double = Math.log10(this)
fun Double.log1p(): Double = Math.log1p(this)
//fun Double.pow(exp: Double): Double = Math.pow(this, exp) // Defined in Koma
fun Double.rint(): Double = Math.rint(this)
fun Double.round(): Long = Math.round(this)
fun Double.scalb(scaleFactor: Int): Double = Math.scalb(this, scaleFactor)
fun Double.sqrt(): Double = Math.sqrt(this)
fun Double.signum(): Double = Math.signum(this)
fun Double.sin(): Double = Math.sin(this)
fun Double.tan(): Double = Math.tan(this)
fun Double.tanh(): Double = Math.tanh(this)
fun Double.toDegrees(): Double = Math.toDegrees(this)
fun Double.toRadians(): Double = Math.toRadians(this)

